name: github pages

on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Create env file
    runs-on: ubuntu-latest
    steps:
      - name: access to secrets
        run: |
          echo "REACT_APP_BACK_END_POINT=${{ secrets.REACT_APP_BACK_END_POINT }}" >> .env
          echo "REACT_APP_PHONE_NUMBER=${{ secrets.REACT_APP_PHONE_NUMBER }}" >> .env
          echo "REACT_APP_EMAIL=${{ secrets.REACT_APP_EMAIL }}" >> .env
          cat .env
        env:
          REACT_APP_BACK_END_POINT: ${{secrets.REACT_APP_BACK_END_POINT}}
          REACT_APP_PHONE_NUMBER: ${{secrets.REACT_APP_PHONE_NUMBER}}
          REACT_APP_EMAIL: ${{secrets.REACT_APP_EMAIL}}

      - run: npm ci
      - run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./dist

